--- 
output_dir: /home/http/www/mutelight.org/public
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# domain to which this site is deployed
base_url: http://mutelight.org

# number of posts to display on front
featured_count: 10

# number of other articles to reference at bottom of each article
other_articles_max: 3

# DISQUS Site Shortname (enables commenting)
disqus_shortname: mutelight-blog

# By default, textile is not considered a "textual" extension
text_extensions: %w( css erb haml htm html js less markdown md php rb sass textile txt )
